#!/usr/local/bin/python3
# -*- coding: utf-8 -*-

import requests
import json

# define my openweather api key
my_api_keys = "d6cc937c6a6994d960d0c1bbbf197446"

# weather emojis
weather_emojis = {
    'Clear': '☀️', 'Clouds': '☁️', 'Rain': '🌧', 'Snow': '❄️', 'Thunderstorm': '⛈', 'Drizzle': '🌦', 'Haze': '🌫', 
    'Mist': '🌫', 'Fog': '🌫', 'Sand': '🏜', 'Dust': '🌪', 'Ash': '🌚', 'Squall': '🌬', 'Tornado': '🌪'
}

# grab my location
resp_ip = requests.get('http://ip-api.com/json/')
data = resp_ip.json()
city = data['city']
lat = data['lat']
lon = data['lon']

# grab the weather for my location
resp_weather = requests.get(f"http://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={my_api_keys}")
weather = json.loads(resp_weather.text)
# grab the weather icon from `weather_emojis`
emojis = weather_emojis.get(weather['weather'][0]['main'], '❓')
# grab the minimum tempreture and maximum tempreture
temp_min = round((weather['main']['temp_min']-273.15), 2)
temp_max = round((weather['main']['temp_max']-273.15), 2)
# grab the weather description
description = weather['weather'][0]['description']
# grab the humidity
humidity = weather['main']['humidity']
# grab the wind speed
wind_speed = weather['wind']['speed']
# grab the wind direction
wind_deg = weather['wind']['deg']
wind_direction = "N" if (wind_deg >= 0 and wind_deg <= 45) or (wind_deg > 315 and wind_deg <= 360) else "E" if wind_deg > 45 and wind_deg <= 135 else "S" if wind_deg > 135 and wind_deg <= 225 else "W"

# print the weather
print(f"tempreture: \033[1;34m{temp_min}-{temp_max}˚C\033[1;0m")
print(f"weather: \033[1;34m{description}\033[1;0m {emojis}")
print(f"humidity: \033[1;34m{humidity}%\033[1;0m")
print(f"wind speed: \033[1;34m{wind_speed}m/s {wind_direction}\033[1;0m")
