#!/usr/local/bin/python3
# -*- coding: utf-8 -*-

import time
import html
import base64
import codecs
import argparse
import urllib.parse

# banner
def banners():
    print('▄▄▄█████▓▓█████ ▒██   ██▒▄▄▄█████▓    ▄████▄   ▒█████   ███▄    █ ██▒   █▓▓█████  ██▀███  ▄▄▄█████▓')
    print('▓  ██▒ ▓▒▓█   ▀ ▒▒ █ █ ▒░▓  ██▒ ▓▒   ▒██▀ ▀█  ▒██▒  ██▒ ██ ▀█   █▓██░   █▒▓█   ▀ ▓██ ▒ ██▒▓  ██▒ ▓▒')
    print('▒ ▓██░ ▒░▒███   ░░  █   ░▒ ▓██░ ▒░   ▒▓█    ▄ ▒██░  ██▒▓██  ▀█ ██▒▓██  █▒░▒███   ▓██ ░▄█ ▒▒ ▓██░ ▒░')
    print('░ ▓██▓ ░ ▒▓█  ▄  ░ █ █ ▒ ░ ▓██▓ ░    ▒▓▓▄ ▄██▒▒██   ██░▓██▒  ▐▌██▒ ▒██ █░░▒▓█  ▄ ▒██▀▀█▄  ░ ▓██▓ ░ ')
    print('  ▒██▒ ░ ░▒████▒▒██▒ ▒██▒  ▒██▒ ░    ▒ ▓███▀ ░░ ████▓▒░▒██░   ▓██░  ▒▀█░  ░▒████▒░██▓ ▒██▒  ▒██▒ ░ ')
    print('  ▒ ░░   ░░ ▒░ ░▒▒ ░ ░▓ ░  ▒ ░░      ░ ░▒ ▒  ░░ ▒░▒░▒░ ░ ▒░   ▒ ▒   ░ ▐░  ░░ ▒░ ░░ ▒▓ ░▒▓░  ▒ ░░   ')
    print('    ░     ░ ░  ░░░   ░▒ ░    ░         ░  ▒     ░ ▒ ▒░ ░ ░░   ░ ▒░  ░ ░░   ░ ░  ░  ░▒ ░ ▒░    ░    ')
    print('                                       \033[1;35m-=Author: Lucas Liu=-\033[1;0m                                       ')

# main function textConvert
def textConvert(text):
    # convertion functions
    rot13 = codecs.encode(text, 'rot13')
    base64Encode = base64.b64encode(text.encode('ascii')).decode('ascii')
    urlEncode = urllib.parse.quote(text)
    htmlEntities = html.escape(text)
    dec = ''.join(str(ord(char)) for char in text)
    hexdec = ''.join('{:02x}'.format(ord(char)) for char in text)
    binary = ''.join(format(ord(char), '08b') for char in text)
    # print out the output as the answers of the convertion
    print('👍\033[1;32mconvertion done. \033[1;0m👍')
    print(f'\033[1;36mROT13: \033[1;0m{rot13}')
    time.sleep(0.5)
    print(f'\033[1;36mBASE64: \033[1;0m{base64Encode}')
    time.sleep(0.5)
    print(f'\033[1;36mURL encode: \033[1;0m{urlEncode}')
    time.sleep(0.5)
    print(f'\033[1;36mHTML entities: \033[1;0m{htmlEntities}')
    time.sleep(0.5)
    print(f'\033[1;36mdecimal: \033[1;0m{dec}')
    time.sleep(0.5)
    print(f'\033[1;36mhexdecimal: \033[1;0m{hexdec}')
    time.sleep(0.5)
    print(f'\033[1;36mbinary: \033[1;0m{binary}')
    time.sleep(0.5)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(formatter_class=argparse.RawTextHelpFormatter, description=banners())
    parser.add_argument('-t', '--text', help='the text/message you want to convert', required=True)
    args = parser.parse_args()
    # calling the main function
    textConvert(args.text)